/***********************************************************************************
 * Common functions needed for all PETScOpenFOAM solvers.
 *
 * Authors: Timothy Costa (Intel Corp.)
 * Date Modified: 8/7/2018
 * *********************************************************************************/

static void
OpenFOAMLDU2PETScCSR(

)
{

}

static void
VecPETSc2OpenFOAM(

)
{

}

static void
VecOpenFOAM2PETSc(

)
{

}
